### ISSUE TITLE
not forwarding stdin for exec commands

### ISSUE THREAD

**Issue by therc** [awslabs/oci-add-hooks#5]
I think this section might be responsible for a bug that has been puzzling lots of people for months:

https://github.com/awslabs/oci-add-hooks/blob/master/main.go#L132

See https://github.com/NVIDIA/nvidia-docker/issues/1091 and https://github.com/awslabs/amazon-eks-ami/issues/453

What I think is going on: dockerd passes the "foo" stdin line from the example to the runtime; in this case, oci-add-hooks is passing through just the stdout/err streams, so runc never sees our message and neither does the process inside the container.

Is the above correct?

**Comment by Jeffwan** [comment]
I think NVIDIA GPU has been natively supported as devices in 19.03 docker, we don't need extra hook for NVIDIA GPU. This is definite a bug for other runtimes oci-add-hooks needs to fix.

**Comment by therc** [comment]
I verified that this patch and a custom RPM are the quickest way to fix deployments with current AMIs:

```
diff --git a/main.go b/main.go
index 1d45f90..31285d1 100644
--- a/main.go
+++ b/main.go
@@ -130,6 +130,7 @@ func processRuncError(err error) int {
 
 func prepareCommand(runcPath string, args []string) *exec.Cmd {
        cmd := exec.Command(runcPath, args...)
+       cmd.Stdin = os.Stdin
        cmd.Stdout = os.Stdout
        cmd.Stderr = os.Stderr
        return cmd
```

**Comment by IRCody** [comment]
Hey @therc, do you want to submit a PR with that fix? Feel free to assign the review to me. Thanks!
